# Generated by Django 3.2.8 on 2021-11-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='parent_message',
            new_name='parent_id',
        ),
    ]
